# Generated by Django 4.2.2 on 2023-06-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personFirstName', models.CharField(max_length=100)),
                ('personLastName', models.CharField(max_length=100)),
                ('personAgeMissing', models.IntegerField()),
                ('personDateMissing', models.DateField()),
                ('personCity', models.CharField(max_length=50)),
                ('personState', models.CharField(max_length=2)),
                ('personGender', models.CharField(max_length=1)),
                ('personRace', models.CharField(max_length=1)),
            ],
        ),
    ]
